version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - yarn global add @angular/cli
      - yarn install
  build:
    commands:
      - ng build --base-href / --output-path ./
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
