export enum UrlPages {
    HOME = 'home',
    AUTH = 'auth',
    LOGIN = 'login',
    REGISTER = 'create-account',
    PASSWORD_RECOVERY = 'password-recovery',
    LANDING = 'landing',
    DASHBOARD = 'dashboard',
    PLANS = 'plans',
    DEVICES = 'devices',
    USERS = 'users',
    ROOMS = 'rooms',
    MAIN = 'main',
    MEDICAL_CENTERS = 'medical-centers',
    MAP = 'live-map',
}